{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
spec:
  selector:
    app: gotenberg-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
{{- end }}
