{{- if .Values.autoscaler.enabled (not .Values.keda.enabled) -}}
# horizontal pod autoscaler for academy-deployment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "a5Chart.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: academy-deployment
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.targetMemoryUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaler.scaleDown.scaleDownStabilizationWindowSeconds }}
      policies:
        - periodSeconds: {{ .Values.autoscaler.scaleDown.shortScaleDownPeriod }}
          type: Pods
          value: {{ .Values.autoscaler.scaleDown.shortScaleDownPodAmount }}
        - periodSeconds: {{ .Values.autoscaler.scaleDown.longScaleDownPeriod }}
          type: Pods
          value: {{ .Values.autoscaler.scaleDown.longScaleDownPeriodPodAmount }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaler.scaleUp.scaleUpStabilizationWindowSeconds }}
      policies:
        - periodSeconds: {{ .Values.autoscaler.scaleUp.longScaleUpPeriod }}
          type: Pods
          value: {{ .Values.autoscaler.scaleUp.longScaleUpPeriodPodAmount }}
        - periodSeconds: {{ .Values.autoscaler.scaleUp.shortScaleUpPeriod }}
          type: Percent
          value: {{ .Values.autoscaler.scaleUp.shortScaleUpPeriodPodPercent }}
{{- end }}
