# horizontal pod autoscaler for academy-deployment
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: academy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: academy-deployment
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaler.targetCPUUtilizationPercentage }}