---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-deployment
spec:
  replicas: {{ .Values.deployment.academyfiveReplicas }}
  selector:
    matchLabels:
      app: academy-app
  template:
    metadata:
      labels:
        app: academy-app
        image-version: {{ .Values.deployment.versionTag }}
    spec:
      serviceAccountName: {{ .Values.deployment.serviceAccountName }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "web"
      containers:
        - name: academy-container
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.versionTag}}
          ports:
            - containerPort: 80
              name: web
          livenessProbe:
            httpGet:
              path: /healthcheck.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: academy-configmap
          volumeMounts:
            - name: infrastructure-config-dir-volume
              mountPath: /run/config
            - name: secret-volume
              mountPath: /mnt/shared-secret-volume
            - name: academy-logs-volume
              mountPath: /srv/a5_source/files/log
            # a5 filestorge mount
            {{- if (eq "file" .Values.infrastructureData.file_storage_type) }}
            - name: academy-files-volume
              mountPath: {{ .Values.infrastructureData.a5_file_storage_location }}
            # cas file_storage mount
            - name: cas-files-volume
              mountPath: {{ .Values.envData.CAS_FILE_STORAGE_LOCATION }}
            {{- end }}
          resources:
            limits:
              memory: {{ .Values.deployment.memoryLimits }}
              cpu: {{ .Values.deployment.cpuLimits }}
            requests:
              memory: {{ .Values.deployment.memoryRequests }}
              cpu: {{ .Values.deployment.cpuRequests }}
        - name: academyfive-academy-logs
          image: busybox
          command: [ "sh","-c","tail -F /srv/a5_source/files/log/academy.log" ]
          volumeMounts:
            - name: academy-logs-volume
              mountPath: /srv/a5_source/files/log
          resources:
            limits:
              cpu: {{ .Values.deployment.academyfiveAcademyLogs.cpuLimits }}
              memory: {{ .Values.deployment.academyfiveAcademyLogs.memoryLimits }}
            requests:
              cpu: {{ .Values.deployment.academyfiveAcademyLogs.cpuRequests }}
              memory: {{ .Values.deployment.academyfiveAcademyLogs.memoryLimits }}
        - name: academyfive-error-logs
          image: busybox
          command: [ "sh","-c","tail -F /srv/a5_source/files/log/error-json.log" ]
          volumeMounts:
            - name: academy-logs-volume
              mountPath: /srv/a5_source/files/log
          resources:
            limits:
              cpu: {{ .Values.deployment.academyfiveErrorLogs.cpuLimits }}
              memory: {{ .Values.deployment.academyfiveErrorLogs.memoryLimits }}
            requests:
              cpu: {{ .Values.deployment.academyfiveErrorLogs.cpuRequests }}
              memory: {{ .Values.deployment.academyfiveErrorLogs.memoryRequests }}
        - name: academyfive-data-access-logs
          image: busybox
          command: [ "sh","-c","tail -F /srv/a5_source/files/log/data-access.log" ]
          volumeMounts:
            - name: academy-logs-volume
              mountPath: /srv/a5_source/files/log
          resources:
            limits:
              cpu: {{ .Values.deployment.academyfiveDataAccessLogs.cpuLimits }}
              memory: {{ .Values.deployment.academyfiveDataAccessLogs.memoryLimits }}
            requests:
              cpu: {{ .Values.deployment.academyfiveDataAccessLogs.cpuRequests }}
              memory: {{ .Values.deployment.academyfiveDataAccessLogs.memoryRequests }}
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: infrastructure-config-dir-volume
          configMap:
            name: academy-infrastructure-config-dir
        - name: secret-volume
          secret:
            secretName: cas-a5-api-shared-secret
        # academy logs volume
        - name: academy-logs-volume
        {{- if .Values.logging.usePersistentVolume }}
          persistentVolumeClaim:
            claimName: academy-logs-pvc-claim
        {{- else }}
          emptyDir:
            # eviction manager keeps monitoring the disk space the emptyDir-Volume and, will evict pods when the usage exceeds the limit.
            sizeLimit: {{ .Values.logging.logSizeLimit }}
        {{- end }}
        # file_storage volume
        {{- if (eq "file" .Values.infrastructureData.file_storage_type) }}
        - name: academy-files-volume
          persistentVolumeClaim:
            claimName: {{ .Values.academy_file_storage_volume.name }}
        {{- if .Values.infrastructureData.cas_file_storage_volume_claim_name }}
        - name: cas-files-volume
          persistentVolumeClaim:
            claimName: {{ .Values.infrastructureData.cas_file_storage_volume_claim_name }}
        {{- end }}
        {{- end }}
