# infrastructure config, mounted as a directory into the academy image
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "a5Chart.infrastructureConfigSecretName" . }}
stringData:
{{- include "a5Chart.tenantConfig" . | nindent 2 }}
