# configmap containing mounted config directory academy image
apiVersion: v1
kind: ConfigMap
metadata:
  name: academy-infrastructure-config-dir
data:
  {{ .Values.global.domain }}: |
    {
    "Url": {{ quote .Values.global.domain }},
    "tenant_id": {{ .Values.global.tenant_id | default .Values.global.domain | quote }},
    "database_type": {{ quote .Values.infrastructureData.database_type }},
    "database_location": {{ quote .Values.infrastructureData.database_write_location }},
    "database_read_location": {{ quote .Values.infrastructureData.database_read_location }},
    "database_write_location": {{ quote .Values.infrastructureData.database_write_location }},
    "filestorage_type": {{ quote .Values.infrastructureData.file_storage_type }},
    {{- if not (eq .Values.infrastructureData.a5_file_storage_location "") }}
    "filestorage_location": {{ quote .Values.infrastructureData.a5_file_storage_location }},
    {{- else }}
    "filestorage_location": "s3://{{.Values.envData.A5_BUCKET_NAME}}",
    {{- end }}
    {{- if not (eq .Values.envData.A5_FILESTORAGE_ENDPOINT_URL "")}}
    "filestorage_endpoint_url": {{ quote .Values.envData.A5_FILESTORAGE_ENDPOINT_URL }},
    {{- end }}
    "oas_a5_domain": {{ quote .Values.infrastructureData.oas_a5_domain }},
    "services_domain": {{ quote .Values.infrastructureData.services_domain }},
    "session_type": {{ quote .Values.infrastructureData.session_type }},
    "session_location": {{ quote .Values.envData.REDIS_SESSION.ENDPOINT }},
    "session_cluster": {{ .Values.envData.REDIS_SESSION.IS_CLUSTER | quote }},
    "cache_type": {{ quote .Values.infrastructureData.cache_type}},
    "cache_location": {
      "clusterType": {{ .Values.envData.REDIS_CACHE.IS_CLUSTER | quote }},
      "url":  {{ quote .Values.envData.REDIS_CACHE.ENDPOINT }}
      {{- if not (eq .Values.envData.REDIS_CACHE.AUTH "no_auth" ) }}
        ,"auth": {{ quote .Values.envData.REDIS_CACHE.AUTH }}
      {{- end }}
    },
    "maintenance_mode": {{ .Values.infrastructureData.maintenance_mode }},
    "aws_region": {{ quote .Values.infrastructureData.aws_region}}
    }
{{- if .Values.global.olddomain }}
  {{ .Values.global.olddomain }}: |
    {
    "Url": {{ quote .Values.global.olddomain }},
    "tenant_id": {{ quote .Values.global.olddomain }},
    "database_type": {{ quote .Values.infrastructureData.database_type }},
    "database_location": {{ quote .Values.infrastructureData.database_write_location }},
    "database_read_location": {{ quote .Values.infrastructureData.database_read_location }},
    "database_write_location": {{ quote .Values.infrastructureData.database_write_location }},
    "filestorage_type": {{ quote .Values.infrastructureData.file_storage_type }},
    {{- if not (eq .Values.infrastructureData.a5_file_storage_location "") }}
    "filestorage_location": {{ quote .Values.infrastructureData.a5_file_storage_location }},
    {{- else }}
    "filestorage_location": "s3://{{.Values.envData.A5_BUCKET_NAME}}",
    {{- end }}
    {{- if not (eq .Values.envData.A5_FILESTORAGE_ENDPOINT_URL "")}}
    "filestorage_endpoint_url": {{ quote .Values.envData.A5_FILESTORAGE_ENDPOINT_URL }},
    {{- end }}
    "oas_a5_domain": {{ quote .Values.infrastructureData.oas_a5_domain }},
    "services_domain": {{ quote .Values.infrastructureData.services_domain }},
    "session_type": {{ quote .Values.infrastructureData.session_type }},
    "session_location": {{ quote .Values.envData.REDIS_SESSION.ENDPOINT }},
    "session_cluster": {{ .Values.envData.REDIS_SESSION.IS_CLUSTER | quote }},
    "cache_type": {{ quote .Values.infrastructureData.cache_type}},
    "cache_location": {
      "clusterType": {{ .Values.envData.REDIS_CACHE.IS_CLUSTER | quote }},
      "url":  {{ quote .Values.envData.REDIS_CACHE.ENDPOINT }}
      {{- if not (eq .Values.envData.REDIS_CACHE.AUTH "no_auth" ) }}
        ,"auth": {{ quote .Values.envData.REDIS_CACHE.AUTH }}
      {{- end }}
    },
    "maintenance_mode": {{ .Values.infrastructureData.maintenance_mode }},
    "aws_region": {{ quote .Values.infrastructureData.aws_region}}
    }
{{- end }}
