# Default values for casChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# hier sind einfach default werte eingetragen für das einzelnes template
envData:
  CAS_A5_API_SECRET_LOCATION: "/mnt/shared-secret-volume/sharedSecret"
  CAS_BUCKET_NAME: "casbucket"
  ASSET_SOURCE: "academy"
  CAS_FILESTORAGE_ENDPOINT_URL: ""
  CAS_FILE_STORAGE_TYPE: "s3"
  CAS_FILE_STORAGE_LOCATION: ""
  METRICS_SCRAPER_IP: ""
  SECRET_REGION: "eu-central-1"
  REDIS_SESSION:
    ENDPOINT: "tcp://<YOUR_REDIS_CLUSTER>"
    IS_CLUSTER: 1
    AUTH: "no_auth"
  REDIS_CACHE:
    ENDPOINT: "tcp://<YOUR_REDIS_CLUSTER>"
    IS_CLUSTER: 1
    AUTH: "no_auth"
deployment:
  replicas: 1
  image: <YOUR_IMAGE_LOCATION>
  versionTag: release-B458
  serviceAccountName: default
  cpuLimits: 2000m
  cpuRequests: 1000m
  memoryLimits: 2G
  memoryRequests: 1G
  casPhpFpmLogs:
    cpuLimits: 250m
    cpuRequests: 10m
    memoryLimits: 256Mi
    memoryRequests: 100Mi
cas_file_storage_volume:
  enabled: false
  name: "cas-file-storage-volume"
  storageClass: "-"
  size: 50Gi
logging:
  # For more information: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
  usePersistentVolume: false
  # EmptyDir-SizeLimit. Will be ignored if usePersistentVolume is true
  logSizeLimit: 500Mi
storage:
  ## Will resolve to storageClassName: <storageClass>
  ## If set to "-" the storageClassName will be omitted and the default storageClass will be used:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
  storageClass: "-"
  size: 2Gi
autoscalerIntegration: "hpa"
autoscaler:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 60
  scaleDown:
    scaleDownStabilizationWindowSeconds: 120
    shortScaleDownPeriod: 30
    shortScaleDownPodAmount: 1
    longScaleDownPeriod: 300
    longScaleDownPeriodPodAmount: 3
  scaleUp:
    scaleUpStabilizationWindowSeconds: 0
    shortScaleUpPeriod: 10
    shortScaleUpPeriodPodPercent: 100
    longScaleUpPeriod: 120
    longScaleUpPeriodPodAmount: 5
service:
  type: ClusterIP
  port: 80
