# Default values for a5Chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envData:
  CAS_A5_API_SECRET_LOCATION: "/mnt/shared-secret-volume/sharedSecret"
  A5_BUCKET_NAME: "a5bucket"
  CAS_BUCKET_NAME: "casbucket"
  CAS_SERVICE_URL: "cas"
  S3_REGION: "eu-central-1"
  ASSET_SOURCE: "academy"
  A5_FILESTORAGE_ENDPOINT_URL: ""
  CAS_FILE_STORAGE_LOCATION: ""
  A5_INFRASTRUCTURE_CONFIG: "/run/config"
  METRICS_SCRAPER_IP: ""
  TIDEWAYS_CONNECTION: "" #tcp://tideways:9135
  TIDEWAYS_API_KEY: ""
  REDIS_SESSION:
    ENDPOINT: "tcp://<YOUR_REDIS_CLUSTER>"
    IS_CLUSTER: 1
    AUTH: "no_auth"
  REDIS_CACHE:
    ENDPOINT: "tcp://<YOUR_REDIS_CLUSTER>"
    IS_CLUSTER: 1
    AUTH: "no_auth"
infrastructureData:
  database_type: "mysql"
  database_read_location: "mysql://<YOUR_READ_USER>:<PASSWORD>@<READER_END_POINT>/<databaseName>"
  database_write_location: "mysql://<YOUR_WRITE_USER>:<PASSWORD>@<WRITER_END_POINT>/<DATABASE_NAME>"
  file_storage_type: "s3"
  cas_file_storage_volume_claim_name: "cas-file-storage-volume"
  a5_file_storage_location: ""
  session_type: "redis"
  session_cluster: true
  cache_type: "redis"
  maintenance_mode: false
  aws_region: "eu-central-1"
migration:
  executeMigration: true
deployment:
  academyfiveReplicas: 1
  image: <YOUR_IMAGE_LOCATION>
  versionTag: V17.11.11
  serviceAccountName: default
  cpuLimits: 4096m
  cpuRequests: 2048m
  memoryLimits: 8G
  memoryRequests: 4G
  academyfiveAcademyLogs:
    cpuLimits: 250m
    cpuRequests: 10m
    memoryLimits: 256Mi
    memoryRequests: 100Mi
  academyfiveErrorLogs:
    cpuLimits: 250m
    cpuRequests: 10m
    memoryLimits: 256Mi
    memoryRequests: 100Mi
  academyfiveDataAccessLogs:
    cpuLimits: 250m
    cpuRequests: 10m
    memoryLimits: 256Mi
    memoryRequests: 100Mi
  cron:
    cpuLimits: 4096m
    cpuRequests: 2048m
    memoryLimits: 32G
    memoryRequests: 16G
academy_file_storage_volume:
  enabled: false
  name: "academy-file-storage-volume"
  storageClass: "-"
  size: 50Gi
logging:
  usePersistentVolume: false
  logSizeLimit: 500Mi
storage:
  storageClass: "-"
  size: 2Gi
autoscalerIntegration: "hpa"
autoscaler:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 60
  scaleDown:
    scaleDownStabilizationWindowSeconds: 120
    shortScaleDownPeriod: 30
    shortScaleDownPodAmount: 1
    longScaleDownPeriod: 300
    longScaleDownPeriodPodAmount: 3
  scaleUp:
    scaleUpStabilizationWindowSeconds: 0
    shortScaleUpPeriod: 10
    shortScaleUpPeriodPodPercent: 100
    longScaleUpPeriod: 120
    longScaleUpPeriodPodAmount: 5
service:
  type: ClusterIP
  port: 80
