apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-academy
  {{- with .Values.ingress.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
    # docs: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#client-header-buffer-size
    nginx.ingress.kubernetes.io/client-body-buffer-size: {{ .Values.ingress.clientBodyBufferSize }}
    # proxy-body-size is client_max_body_size
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxyBodySize }}
    nginx.ingress.kubernetes.io/client-body-timeout: "36000"
    nginx.ingress.kubernetes.io/large-client-header-buffers: {{ .Values.ingress.largeClientHeaderBuffers }}
    nginx.ingress.kubernetes.io/client-header-buffer-size: {{ .Values.ingress.clientHeaderBufferSize }}
    nginx.ingress.kubernetes.io/client-header-timeout: "36000"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ quote .Values.ingress.proxyConnectTimeout }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ quote .Values.ingress.proxyReadTimeout }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ quote .Values.ingress.proxySendTimeout }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Ingress-Resource "ingress-academy"; 

    # Speed settings
    nginx.ingress.kubernetes.io/keep-alive: "5"
    nginx.ingress.kubernetes.io/keep-alive-requests: "10000"
    nginx.ingress.kubernetes.io/use-gzip: "true"
    nginx.ingress.kubernetes.io/gzip-level: "6"
    nginx.ingress.kubernetes.io/use-http2: "true"

spec:
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ quote .Values.global.hosts }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: academy
                port:
                  number: 80
{{- if .Values.global.olddomain }}
    - host: {{ .Values.global.olddomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: academy
                port:
                  number: 80
{{- end }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
