# Default values for secretChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
secret:
  # must match cas_a5_api_secret_name in a5Chart and casChart
  cas_a5_api_secret_name: "cas-a5-api-shared-secret"
data:
  sharedSecret: <YOUR_SECRET>
