# Default values for casIngress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

casHosts:
  - name: example-application.academyfive.net
  - name: example-pwa.academyfive.net
  - name: example-community.academyfive.net

ingress:
  #If required provide your own labels and annotations
  labels: {}
    #examplelabel: examplevalue
  annotations: {}
    #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    #alb.ingress.kubernetes.io/ssl-redirect: '443'
    #alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:your-certificate-arn
    #alb.ingress.kubernetes.io/scheme: internet-facing
    #alb.ingress.kubernetes.io/target-type: ip
  tlsSecretName: academyfive.net-tls
  ingressClassName: nginx
  proxyBuffering: "on"
  authKeepaliveRequests: "10000"
  clientBodyBufferSize: "100M"
  proxyBodySize: "500M"
  proxyConnectTimeout: "600"
  proxyReadTimeout: "600"
  proxySendTimeout: "600"
