# Default values for casIngress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

casHosts:
  - name: example-application.academyfive.net
  - name: example-pwa.academyfive.net
  - name: example-community.academyfive.net

ingress:
  proxyBuffering: "off"
  authKeepaliveRequests: "10000"
  clientBodyBufferSize: "100M"
  proxyBodySize: "500M"
  proxyConnectTimeout: "600"
  proxyReadTimeout: "600"
  proxySendTimeout: "600"
