# Default values for academyfive.
# This is a YAML-formatted file.
#

global:
  domain: "a5.university.com"
  hosts: "*.university.com"

a5Chart:
  enabled: true
  envData:
    A5_BUCKET_NAME: "a5bucket"
    CAS_BUCKET_NAME: "casbucket"
    A5_FILESTORAGE_ENDPOINT_URL: ""
    REDIS_SESSION:
      ENDPOINT: "tcp://<YOUR_REDIS_CLUSTER>"
      IS_CLUSTER: 1
      AUTH: "no_auth"
    REDIS_CACHE:
      ENDPOINT: "tcp://<YOUR_REDIS_CLUSTER>"
      IS_CLUSTER: 1
      AUTH: "no_auth"

  infrastructureData:
    database_read_location: "mysql://<YOUR_READ_USER>:<PASSWORD>@<READER_END_POINT>/<DATABASE_NAME>"
    database_write_location: "mysql://<YOUR_WRITE_USER>:<PASSWORD>@<WRITER_END_POINT>/<DATABASE_NAME>"

  deployment:
    academyfiveReplicas: 1
    image: <YOUR_IMAGE_LOCATION>

    # OVERRIDE LIMIT VALUES HERE

    # cpuLimits: 4096m
    # cpuRequests: 2048m
    # memoryLimits: 8G
    # memoryRequests: 4G
    # academyfiveAcademyLogs:
    #   cpuLimits: 250m
    #   cpuRequests: 10m
    #   memoryLimits: 256Mi
    #   memoryRequests: 100Mi
    # academyfiveErrorLogs:
    #   cpuLimits: 250m
    #   cpuRequests: 10m
    #   memoryLimits: 256Mi
    #   memoryRequests: 100Mi
    # academyfiveDataAccessLogs:
    #   cpuLimits: 250m
    #   cpuRequests: 10m
    #   memoryLimits: 256Mi
    #   memoryRequests: 100Mi
    # cron:
    #   cpuLimits: 4096m
    #   cpuRequests: 2048m
    #   memoryLimits: 32G
    #   memoryRequests: 16G

  logging:
    # Will create an emptyDir volume for logs if set to false or a persistentVolumeClaim if set to true
    # For more information: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
    usePersistentVolume: false
    # EmptyDir-SizeLimit. Will be ignored if usePersistentVolume is true
    logSizeLimit: 500Mi

  # can be omitted if logging.usePersistentVolume is false
  storage:
    ## Will resolve to storageClassName: <storageClass>
    ## If set to "-" the storageClassName will be omitted and the default storageClass will be used:
    # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
    storageClass: "-"
    size: 2Gi

  autoscaler:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 40

  keda:
    enabled: false

casChart:
  enabled: true
  envData:
    CAS_FILESTORAGE_ENDPOINT_URL: ""
    CAS_BUCKET_NAME: "casbucket"
    REDIS_SESSION:
      ENDPOINT: "tcp://<YOUR_REDIS_CLUSTER>"
      IS_CLUSTER: 1
      AUTH: "no_auth"
    REDIS_CACHE:
      ENDPOINT: "tcp://<YOUR_REDIS_CLUSTER>"
      IS_CLUSTER: 1
      AUTH: "no_auth"

  logging:
    # For more information: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
    usePersistentVolume: false
    # EmptyDir-SizeLimit. Will be ignored if usePersistentVolume is true
    logSizeLimit: 500Mi

  storage:
    ## Will resolve to storageClassName: <storageClass>
    ## If set to "-" the storageClassName will be omitted and the default storageClass will be used:
    # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
    storageClass: "-"
    size: 2Gi
  autoscaler:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

  keda:
    enabled: false

  deployment:
    image: <YOUR_IMAGE_LOCATION>

    # OVERRIDE LIMIT VALUES HERE

    # cpuLimits: 2000m
    # cpuRequests: 1000m
    # memoryLimits: 2G
    # memoryRequests: 1G
    # casPhpFpmLogs:
    #   cpuLimits: 250m
    #   cpuRequests: 10m
    #   memoryLimits: 256Mi
    #   memoryRequests: 100Mi

a5Ingress:
  enabled: true

casIngress:
  enabled: true
  casHosts:
    - name: application.university.com
    - name: community.university.com
    - name: pwa.university.com

sharedResourcesNginx:
  enabled: true
  ssl:
    tlsCertificateChain: <YOUR_CERT_CHAIN>
    tlsKey: <YOUR_KEY>
secretChart:
  enabled: true
  data:
    sharedSecret: <YOUR_SECRET>
