---
# configmap containing all env variables for cas image
apiVersion: v1
kind: ConfigMap
metadata:
  name: cas-configmap
data:
  #CAS_DEPLOYMENT_TYPE: "onpremise"
  CAS_A5_API_SECRET_LOCATION: {{ .Values.envData.CAS_A5_API_SECRET_LOCATION }}
  # CAS_A5_API_PROTOCOL: can only be http or https. Set to http when routing traffic inside the cluster
  CAS_A5_API_PROTOCOL: {{ .Values.envData.CAS_A5_API_PROTOCOL | default "https" }}
  CAS_BUCKET_NAME: {{ .Values.envData.CAS_BUCKET_NAME }}
  ASSET_SOURCE: {{ .Values.envData.ASSET_SOURCE }}
  S3_ASSETS_URL: {{ .Values.envData.S3_ASSETS_URL | default .Values.global.domain }}
  {{- if not (eq .Values.envData.CAS_FILESTORAGE_ENDPOINT_URL "")}}
  CAS_FILESTORAGE_ENDPOINT_URL: {{ .Values.envData.CAS_FILESTORAGE_ENDPOINT_URL }}
  {{- end }}
  CAS_FILE_STORAGE_TYPE: {{ .Values.envData.CAS_FILE_STORAGE_TYPE }}
  {{- if not (eq .Values.envData.CAS_FILE_STORAGE_LOCATION "") }}
  CAS_FILE_STORAGE_LOCATION: {{ .Values.envData.CAS_FILE_STORAGE_LOCATION }}
  {{- end }}
  {{- if not (eq .Values.envData.METRICS_SCRAPER_IP "")}}
  METRICS_SCRAPER_IP: {{ .Values.envData.METRICS_SCRAPER_IP }}
  {{- end }}
  SECRET_REGION: {{ .Values.envData.SECRET_REGION }}
  REDIS_SESSION_ENDPOINT: {{ .Values.envData.REDIS_SESSION.ENDPOINT }}
  REDIS_SESSION_IS_CLUSTER: {{ .Values.envData.REDIS_SESSION.IS_CLUSTER | quote }}
  {{- if not (eq .Values.envData.REDIS_SESSION.AUTH "no_auth" ) }}
  REDIS_SESSION_AUTH: {{ quote .Values.envData.REDIS_SESSION.AUTH }}
  {{- end }}
  REDIS_CACHE_ENDPOINT: {{ .Values.envData.REDIS_CACHE.ENDPOINT }}
  REDIS_CACHE_IS_CLUSTER: {{ .Values.envData.REDIS_CACHE.IS_CLUSTER | quote }}
  {{- if not (eq .Values.envData.REDIS_CACHE.AUTH "no_auth" ) }}
  REDIS_CACHE_AUTH: {{ quote .Values.envData.REDIS_CACHE.AUTH }}
  {{- end }}
  {{- if not (eq .Values.global.ca_cert_file "") }}
  CA_CERT_FILE: {{ .Values.global.ca_cert_file }}
  CA_CERT_VALUE: {{ .Values.global.ca_cert_value }}
  {{- end }}
  CAS_NESTED_PROXY_COUNT: {{ .Values.envData.CAS_NESTED_PROXY_COUNT | quote }}
