{{- if .Values.cas_file_storage_volume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name uniquely identifies the PVC. This is used in deployment.
  name: {{ .Values.cas_file_storage_volume.name }}
spec:
  {{- if not (eq "-" .Values.cas_file_storage_volume.storageClass) }}
  storageClassName: "{{ .Values.cas_file_storage_volume.storageClass }}"
  {{- end }}
  accessModes:
    # The volume is mounted as read-write by Multiple nodes
    - ReadWriteMany
  resources:
    # This is the request for storage. Should be available in the cluster.
    requests:
      storage: {{ .Values.cas_file_storage_volume.size }}
{{- end }}