---
apiVersion: v1
data:
  # shared-secret is the name of the file that will contain the secret. must be base64-encoded
  sharedSecret: {{ .Values.data.sharedSecret | b64enc | quote }}
kind: Secret
metadata:
  name: cas-a5-api-shared-secret
