---
apiVersion: v1
data:
  # shared-secret is the name of the file that will contain the secret. must be base64-encoded
  sharedSecret: {{ .Values.data.sharedSecret | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.secret.cas_a5_api_secret_name }}
