apiVersion: v2
name: nginxControllerConfig
description: Manages the ConfigMap consumed by the NGINX Ingress Controller (F5/NGINX Inc.) used by academyfive

type: application

version: 1.0.0

appVersion: "1.0.0"
